modLoader = "javafml" #mandatory
loaderVersion = "[${forge_major},)"
license = "https://www.curseforge.com/project/363543/license"
issueTrackerURL = "https://github.com/DivineRPG/DivineRPG/issues" #optional

[[mods]] #mandatory
modId = "divinerpg" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "DivineRPG" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/DivineRPG/DivineRPG/1.12.2/divinerpg_update.json" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/official-divinerpg" #optional
logoFile = "logo.png" #optional
credits = "https://github.com/DivineRPG/DivineRPG/blob/1.12.2/credits.md" #optional
description = '''Adds various dimensions, weapons, and mobs'''

[[dependencies.divinerpg]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[${forge_major},)" #mandatory
ordering = "NONE"
side = "BOTH"
